In [0]:
⊖ Everything running smoothly! 
This tutorial was contributed by Justin Johnson.
We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.
We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.
Some of you may have previous knowledge in Matlab, in which case we also recommend the numpy for Matlab users page.
You can also find an IPython notebook version of this tutorial here created by Volodymyr Kuleshov and Isaac Caswell for CS 228.
Table of contents:
Python
Basic data types
Containers
Lists
Dictionaries
Sets
Tuples
Functions
Classes
Numpy
Arrays
Array indexing
Datatypes
Array math
Broadcasting
SciPy
Image operations
MATLAB files
Distance between points
Matplotlib
Plotting
Subplots
Images
Python¶ 
Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:
In [ ]:
def mlblr_in_quicksort(arr_eip):
    if len(arr_eip) <= 1:
        return arr_eip
     pivot_eip= arr_eip[len(arr_eip) // 2]
    left_eip = [x for x in arr_eip if x < pivot_eip]	
    middle_eip = [x for x in arr_eip if x == pivot_eip]
    right_eip = [x for x in arr_eip if x > pivot_eip]
    return mlblr_in_quicksort(left_eip) + middle_eip + mlblr_in_quicksort(right_eip)

print(mlblr_in_quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"
Python versions¶ 
There are currently two different supported versions of Python, 2.7 and 3.5. Somewhat confusingly, Python 3.0 introduced many backwards-incompatible changes to the language, so code written for 2.7 may not work under 3.5 and vice versa. For this class all code will use Python 3.5.
You can check your Python version at the command line by running python --version.
Basic data types¶ 
Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.
Numbers: Integers and floats work as you would expect from other languages:
In [ ]:
x_eip = 3
print(type(x_eip)) # Prints "<class 'int'>"
print(x_eip)       # Prints "3"
print(x_eip + 1)   # Addition; prints "4"
print(x_eip - 1)   # Subtraction; prints "2"
print(x_eip * 2)   # Multiplication; prints "6"
print(x_eip ** 2)  # Exponentiation; prints "9"
x_eip += 1
print(x_eip)  # Prints "4"
x_eip *= 2
print(x_eip)  # Prints "8"
y_eip = 2.5
print(type(y_eip)) # Prints "<class 'float'>"
print(y_eip, y_eip + 1, y_eip * 2, y_eip ** 2) # Prints "2.5 3.5 5.0 6.25"
Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.
Python also has built-in types for complex numbers; you can find all of the details in the documentation.
Booleans: Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):
In [ ]:
t_eip = True
f_eip = False
print(type(t_eip)) # Prints "<class 'bool'>"
print(t_eip and f_eip) # Logical AND; prints "False"
print(t_eip or f_eip)  # Logical OR; prints "True"
print(not t_eip)   # Logical NOT; prints "False"
print(t_eip != f_eip)  # Logical XOR; prints "True"
Strings: Python has great support for strings:
In [ ]:
hello_eip = 'hello'    # String literals can use single quotes
world_eip = "world"    # or double quotes; it does not matter.
print(hello_eip)       # Prints "hello"
print(len(hello_eip))  # String length; prints "5"
hw_eip = hello_eip + ' ' + world_eip  # String concatenation
print(hw_eip)  # prints "hello world"
hw_eip12 = '%s %s %d' % (hello_eip, world_eip, 12)  # sprintf style string formatting
print(hw_eip12)  # prints "hello world 12"
String objects have a bunch of useful methods; for example:
In [ ]:
eip_str = "hello"
print(eip_str.capitalize())  # Capitalize a string; prints "Hello"
print(eip_str.upper())       # Convert a string to uppercase; prints "HELLO"
print(eip_str.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(eip_str.center(7))     # Center a string, padding with spaces; prints " hello "
print(eip_str.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"
You can find a list of all string methods in the documentation.
Containers¶ 
Python includes several built-in container types: lists, dictionaries, sets, and tuples.
Lists¶ 
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:
In [ ]:
eip_list_xs= [3, 1, 2]    # Create a list
print(eip_list_xs, eip_list_xs [2])  # Prints "[3, 1, 2] 2"
print(eip_list_xs [-1])     # Negative indices count from the end of the list; prints "2"
eip_list_xs [2] = 'foo'     # Lists can contain elements of different types
print(eip_list_xs)         # Prints "[3, 1, 'foo']"
eip_list_xs.append('bar')  # Add a new element to the end of the list
print(eip_list_xs)         # Prints "[3, 1, 'foo', 'bar']"
x = eip_list_xs.pop()      # Remove and return the last element of the list
print(x, eip_list_xs)      # Prints "bar [3, 1, 'foo']"
As usual, you can find all the gory details about lists in the documentation.
Slicing: In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:
In [ ]:
nums_eip = list(range(5))     # range is a built-in function that creates a list of integers
print(nums_eip)               # Prints "[0, 1, 2, 3, 4]"
print(nums_eip[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums_eip[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums_eip[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums_eip[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums_eip[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums_eip[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums_eip)               # Prints "[0, 1, 8, 9, 4]"
We will see slicing again in the context of numpy arrays.
Loops: You can loop over the elements of a list like this:
In [ ]:
animals_eip = ['cat', 'dog', 'monkey']
for animal in animals_eip:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.
If you want access to the index of each element within the body of a loop, use the built-in enumerate function:
In [ ]:
animals_eip = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals_eip):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line
List comprehensions: When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:
In [ ]:
nums_eip_list = [0, 1, 2, 3, 4]
squares_eip = []
for x in nums_eip_list:
    squares _eip.append(x ** 2)
print(squares _eip)   # Prints [0, 1, 4, 9, 16]
You can make this code simpler using a list comprehension:
In [ ]:
nums _eip = [0, 1, 2, 3, 4]
squares _eip = [x ** 2 for x in nums _eip]
print(squares _eip)   # Prints [0, 1, 4, 9, 16]
List comprehensions can also contain conditions:
In [ ]:
num _eip = [0, 1, 2, 3, 4]
even_squares_eip= [x ** 2 for x in num_eip if x % 2 == 0]
print(even_squares_eip)  # Prints "[0, 4, 16]"
Dictionaries¶ 
A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:
In [ ]:
eip_dict _d= {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(eip_dict_d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in eip_dict_d)     # Check if a dictionary has a given key; prints "True"
eip_dict_d['fish'] = 'wet'     # Set an entry in a dictionary
print(eip_dict _d['fish'])      # Prints "wet"
# print(eip_dict _d['monkey'])  # KeyError: 'monkey' not a key of d
print(eip_dict_d.get('monkey', 'N/A'))  # Get an element with a eip_dict_default; prints "N/A"
print(eip_dict_d.get('fish', 'N/A'))    # Get an element with a eip_dict_default; prints "wet"
del eip_dict_d['fish']         # Remove an element from a dictionary
print(¬ eip_dict_d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"
You can find all you need to know about dictionaries in the documentation.
Loops: It is easy to iterate over the keys in a dictionary:
In [ ]:
eip_dict_d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in eip_dict_d:
    legs = eip_dict_d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"
If you want access to keys and their corresponding values, use the items method:
In [ ]:
eip_dict_d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in eip_dict_d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"
Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:
In [ ]:
nums _eip = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums _eip if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"
Sets¶ 
A set is an unordered collection of distinct elements. As a simple example, consider the following:
In [ ]:
eip_animals_set = {'cat', 'dog'}
print('cat' in eip_animals_set)   # Check if an element is in a set; prints "True"
print('fish' in eip_animals_set)  # prints "False"
eip_animals_set.add('fish')       # Add an element to a set
print('fish' in eip_animals_set)  # Prints "True"
print(len(eip_animals_set))       # Number of elements in a set; prints "3"
eip_animals_set.add('cat')        # Adding an element that is already in the set does nothing
print(len(eip_animals_set))       # Prints "3"
eip_animals_set.remove('cat')     # Remove an element from a set
print(len(eip_animals_set))       # Prints "2"
As usual, everything you want to know about sets can be found in the documentation.
Loops: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:
In [ ]:
eip_animals_set = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(eip_animals_set):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"
Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:
In [ ]:
from math import sqrt
eip_set_nums = {int(sqrt(x)) for x in range(30)}
print(eip_set_nums)  # Prints "{0, 1, 2, 3, 4, 5}"
Tuples¶ 
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:
In [ ]:
eip_dictionary_d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
eip_tuples_t = (5, 6)        # Create a tuple
print(type(eip_tuples_t))    # Prints "<class 'tuple'>"
print(eip_dictionary_d[eip_tuples_t])       # Prints "5"
print(eip_dictionary_d[(1, 2)])  # Prints "1"
The documentation has more information about tuples.
Functions¶ 
Python functions are defined using the def keyword. For example:
In [ ]:
def mlblr_sign(x_eip):
    if x_eip > 0:
        return 'positive'
    elif x_eip < 0:
        return 'negative'
    else:
        return 'zero'

for x_eip in [-1, 0, 1]:
    print(mlblr_sign(x_eip))
# Prints "negative", "zero", "positive"
We will often define functions to take optional keyword arguments, like this:
In [ ]:
def mlblr_hello(name_eip, loud_eip=False):
    if loud_eip:
        print('HELLO, %s!' % name_eip.upper())
    else:
        print('Hello, %s' % name_eip)

mlblr_hello('Bob') # Prints "Hello, Bob"
mlblr_hello('Fred', loud_eip=True)  # Prints "HELLO, FRED!"
There is a lot more information about Python functions in the documentation.
Classes¶ 
The syntax for defining classes in Python is straightforward:
In [ ]:
class Mlblr_Greeter(object):

    # Constructor
    def __init__(self, name_eip):
        self.name_eip = name_eip  # Create an instance variable

    # Instance method
    def greet(self, loud_eip=False):
        if loud_eip:
            print('HELLO, %s!' % self.name_eip.upper())
        else:
            print('Hello, %s' % self.name_eip)

eip_g = Mlblr_Greeter('Fred')  # Construct an instance of the Greeter class
eip_g.greet()            # Call an instance method; prints "Hello, Fred"
eip_g.greet(loud_eip=True)   # Call an instance method; prints "HELLO, FRED!"
You can read a lot more about Python classes in the documentation.
Numpy¶ 
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.
Arrays¶ 
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:
In [ ]:
import numpy as np

eip_a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(eip_a))            # Prints "<class 'numpy.ndarray'>"
print(eip_a.shape)            # Prints "(3,)"
print(eip_a[0], eip_a[1], eip_a[2])   # Prints "1 2 3"
eip_a[0] = 5                  # Change an element of the array
print(eip_a)                  # Prints "[5, 2, 3]"

eip_b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(eip_b.shape)                     # Prints "(2, 3)"
print(eip_b[0, 0], eip_b[0, 1], eip_b[1, 0])   # Prints "1 2 4"
Numpy also provides many functions to create arrays:
In [ ]:
import numpy as np

eip_a = np.zeros((2,2))   # Create an array of all zeros
print(eip_a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

eip_b = np.ones((1,2))    # Create an array of all ones
print(eip_b)              # Prints "[[ 1.  1.]]"

eip_c = np.full((2,2), 7)  # Create a constant array
print(eip_c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

eip_d = np.eye(2)         # Create a 2x2 identity matrix
print(eip_d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

eip_e = np.random.random((2,2))  # Create an array filled with random values
print(eip_e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"
You can read about other methods of array creation in the documentation.
Array indexing¶ 
Numpy offers several ways to index into arrays.
Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:
In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip_a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
eip_b = eip_a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(eip_a[0, 1])   # Prints "2"
eip_b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(eip_a[0, 1])   # Prints "77"
You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:
In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip_a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = eip_a[1, :]    # Rank 1 view of the second row of a
row_r2 = eip_a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = eip_a[:, 1]
col_r2 = eip_a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"
Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:
In [ ]:
import numpy as np

eip_a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(eip_a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([eip_a[0, 0], eip_a[1, 1], eip_a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(eip_a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([eip_a[0, 1], eip_a[0, 1]]))  # Prints "[2 2]"
One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:
In [ ]:
import numpy as np

# Create a new array from which we will select elements
eip_a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(eip_a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
eip_b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(eip_a[np.arange(4), eip_b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), eip_b] += 10

print(eip_a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])
Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:
In [ ]:
import numpy as np

eip_a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (eip_a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(eip_a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(eip_a[eip_a > 2])     # Prints "[3 4 5 6]"
For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.
Datatypes¶ 
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:
In [ ]:
import numpy as np

x_eip = np.array([1, 2])   # Let numpy choose the datatype
print(x_eip.dtype)         # Prints "int64"

x_eip = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x_eip.dtype)             # Prints "float64"

x_eip = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x_eip.dtype)                         # Prints "int64"
You can read all about numpy datatypes in the documentation.
Array math¶ 
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:
In [ ]:
import numpy as np

x_eip = np.array([[1,2],[3,4]], dtype=np.float64)
y_eip = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x_eip + y_eip)
print(np.add(x_eip, y_eip))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x_eip - y_eip)
print(np.subtract(x_eip, y_eip))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x_eip * y_eip)
print(np.multiply(x_eip, y_eip))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x_eip / y_eip)
print(np.divide(x_eip, y_eip))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x_eip))
Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:
In [ ]:
import numpy as np

x_eip = np.array([[1,2],[3,4]])
y_eip = np.array([[5,6],[7,8]])

v_eip = np.array([9,10])
w_eip = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v_eip.dot(w_eip))
print(np.dot(v_eip, w_eip))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x_eip.dot(v_eip))
print(np.dot(x_eip, v_eip))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x_eip.dot(y_eip))
print(np.dot(x_eip, y_eip))
Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:
In [ ]:
import numpy as np

x_eip = np.array([[1,2],[3,4]])

print(np.sum(x_eip))  # Compute sum of all elements; prints "10"
print(np.sum(x_eip, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x_eip, axis=1))  # Compute sum of each row; prints "[3 7]"
You can find the full list of mathematical functions provided by numpy in the documentation.
Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:
In [ ]:
import numpy as np

x_eip = np.array([[1,2], [3,4]])
print(x_eip)    # Prints "[[1 2]
            #          [3 4]]"
print(x_eip.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v_eip = np.array([1,2,3])
print(v_eip)    # Prints "[1 2 3]"
print(v_eip.T)  # Prints "[1 2 3]"
Numpy provides many more functions for manipulating arrays; you can see the full list in the documentation.
Broadcasting¶ 
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:
In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x_eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v_eip = np.array([1, 0, 1])
y_eip = np.empty_like(x_eip)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y_eip[i, :] = x_eip[i, :] + v_eip

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y_eip)
This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:
In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x_eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v_eip = np.array([1, 0, 1])
v_eipv = np.tile(v_eip, (4, 1))   # Stack 4 copies of v on top of each other
print(v_eipv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y_eip = x_eip + v_eipv  # Add x and vv elementwise
print(y_eip)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:
In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x_eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v_eip = np.array([1, 0, 1])
y_eip = x_eip + v_eip  # Add v to each row of x using broadcasting
print(y_eip)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.
Broadcasting two arrays together follows these rules:
If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
If this explanation does not make sense, try reading the explanation from the documentation or this explanation.
Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.
Here are some applications of broadcasting:
In [ ]:
import numpy as np

# Compute outer product of vectors
v_eip = np.array([1,2,3])  # v has shape (3,)
w_eip = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v_eip, (3, 1)) * w_eip)

# Add a vector to each row of a matrix
x_eip = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x_eip + v_eip)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x_eip.T + w_eip).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x_eip + np.reshape(w_eip, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x_eip * 2)
Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.
Numpy Documentation¶ 
This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the numpy reference to find out much more about numpy.
SciPy¶ 
Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.
The best way to get familiar with SciPy is to browse the documentation. We will highlight some parts of SciPy that you might find useful for this class.
Image operations¶ 
SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:
In [ ]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img_mlblr = imread('assets/cat.jpg')
print(img_mlblr.dtype, img_mlblr.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_mlblr_tinted = img_mlblr * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_mlblr_tinted = imresize(img_mlblr_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_mlblr_tinted)
  
Left: The original image. Right: The tinted and resized image. 
MATLAB files¶ 
The functions scipy.io.loadmat and scipy.io.savemat allow you to read and write MATLAB files. You can read about them in the documentation.
Distance between points¶ 
SciPy defines some useful functions for computing distances between sets of points.
The function scipy.spatial.distance.pdist computes the distance between all pairs of points in a given set:
In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
x_eip = np.array([[0, 1], [1, 0], [2, 0]])
print(x_eip)

# Compute the Euclidean distance between all rows of x.
# eip_d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
eip_d = squareform(pdist(x_eip, 'euclidean'))
print(eip_d)
You can read all the details about this function in the documentation.
A similar function (scipy.spatial.distance.cdist) computes the distance between all pairs across two sets of points; you can read about it in the documentation.
Matplotlib¶ 
Matplotlib is a plotting library. In this section give a brief introduction to the matplotlib.pyplot module, which provides a plotting system similar to that of MATLAB.
Plotting¶ 
The most important function in matplotlib is plot, which allows you to plot 2D data. Here is a simple example:
In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on a sine curve
x_eip = np.arange(0, 3 * np.pi, 0.1)
y_eip = np.sin(x_eip)

# Plot the points using matplotlib
plt.plot(x_eip, y_eip)
plt.show()  # You must call plt.show() to make graphics appear.
Running this code produces the following plot:
 
With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:
In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x_eip = np.arange(0, 3 * np.pi, 0.1)
y_eip_sin = np.sin(x_eip)
y_eip_cos = np.cos(x_eip)

# Plot the points using matplotlib
plt.plot(x_eip, y_eip_sin)
plt.plot(x_eip, y_eip_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()
 
You can read much more about the plot function in the documentation.
Subplots¶ 
You can plot different things in the same figure using the subplot function. Here is an example:
In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x_eip = np.arange(0, 3 * np.pi, 0.1)
y_eip_sin = np.sin(x_eip)
y_eip_cos = np.cos(x_eip)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x_eip, y_eip_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x_eip, y_eip_cos)
plt.title('Cosine')

# Show the figure.
plt.show()
 
You can read much more about the subplot function in the documentation.
Images¶ 
You can use the imshow function to show images. Here is an example:
In [ ]:
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img_mlblr = imread('assets/cat.jpg')
img_mlblr_tinted = img_mlblr * [1, 0.95, 0.9]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img_mlblr)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_mlblr_tinted))
plt.show()
 

